on:
  push:
    branches:
      - UAT # Change this to your respective branch
permissions:
  id-token: write
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify build started
        uses: aliencube/microsoft-teams-actions@v0.8.0 #  or "./" if in a local set-up
        if: always()
        with:
          webhook_uri: https://poonawallafincorp.webhook.office.com/webhookb2/efdaf8b5-8df0-4bb7-bc59-22795a77abcf@3b3240ed-529f-4a11-980d-4cfdc12284c3/IncomingWebhook/15aa4b84ef5546029f16a2434dc501e8/d11b0912-f394-4e1b-89ae-ecb5cdc24966/V2Q0lMysBF_U-jeJ_d8GPWlvN9KuFEHmiOr2184cSTDY01
          title: Commit by ${{ github.event.commits[0].author.name }} in ${{ github.repository }}
          sections: '[{ "title": " View Workflow run :- ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }, { "Commit By": "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com" }]'
          summary: ' Commit by ${github.event.commits[0].author.name} in ${{ github.repository }} on branch ${GITHUB_REF##*/}  '
  build:
    needs: notify
    if: always()
    runs-on: [self-hosted, actions_runner_uat_ds_web]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #Login to docker and push to ecr
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::500440857146:role/github_ds_role
          aws-region: ap-south-1
      - uses: int128/create-ecr-repository-action@v1
        id: ecr
        with:
          repository: uat_api-tester

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 500440857146.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: 500440857146.dkr.ecr.ap-south-1.amazonaws.com
          REPOSITORY: uat_api-tester
        run: |
          docker build -t $REGISTRY/$REPOSITORY:${{ github.sha }} .
          docker push $REGISTRY/$REPOSITORY:${{ github.sha }}

      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.29.0'
        id: install

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          rm /tmp/awscliv2.zip
          sudo /tmp/aws/install --update
          rm -rf /tmp/aws/

      - name: Update context
        run: aws eks update-kubeconfig --region ap-south-1 --name PFL-UAT-Web-digital-Platform

      - name: Deploy to K8s
        run: |
          kubectl get pods -A     #optional
          kubectl apply -f Deployment.yaml -n uat-api
          kubectl set image deployment/api-tester api-tester=500440857146.dkr.ecr.ap-south-1.amazonaws.com/uat_api-tester:${{ github.sha }} -n uat-api

  result:
    runs-on: ubuntu-latest
    if: always()
    needs: build
    steps:
      - name: Notify build started
        uses: aliencube/microsoft-teams-actions@v0.8.0 #  or "./" if in a local set-up
        if: always()
        with:
          webhook_uri: https://poonawallafincorp.webhook.office.com/webhookb2/efdaf8b5-8df0-4bb7-bc59-22795a77abcf@3b3240ed-529f-4a11-980d-4cfdc12284c3/IncomingWebhook/15aa4b84ef5546029f16a2434dc501e8/d11b0912-f394-4e1b-89ae-ecb5cdc24966/V2Q0lMysBF_U-jeJ_d8GPWlvN9KuFEHmiOr2184cSTDY01
          title: Commit by ${{ github.event.commits[0].author.name }} in ${{ github.repository }} and the outcome is ${{ needs.build.result }}.
          sections: '[{ "title": " View Workflow run :- ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }, { "Commit By": "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com" }]'
          summary: ' Commit by ${github.event.commits[0].author.name} in ${{ github.repository }} on branch ${GITHUB_REF##*/}  '
